name: Test
on: [push, pull_request]
jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.distro }} ${{ matrix.image }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os:
        #   - ubuntu-20.04 # focal
        #   - ubuntu-18.04 # bionic
        #   - ubuntu-16.04 # xenial
        include:
          - {os: ubuntu-20.04, distro: fedora, image: 'docker.io/fedora:33'}
          - {os: ubuntu-20.04, distro: fedora, image: 'registry.fedoraproject.org/fedora:33'}
          - {os: ubuntu-20.04, distro: fedora, image: 'docker.io/fedora:34'}
          - {os: ubuntu-20.04, distro: fedora, image: 'registry.fedoraproject.org/fedora:34'}
          - {os: ubuntu-18.04, distro: fedora, image: 'docker.io/fedora:34'}
          - {os: ubuntu-18.04, distro: fedora, image: 'registry.fedoraproject.org/fedora:34'}
          - {os: ubuntu-16.04, distro: fedora, image: 'docker.io/fedora:34'}
          - {os: ubuntu-16.04, distro: fedora, image: 'registry.fedoraproject.org/fedora:34'}
          - {os: ubuntu-20.04, distro: fedora, image: 'docker.io/fedora:rawhide'}
          - {os: ubuntu-20.04, distro: fedora, image: 'registry.fedoraproject.org/fedora:rawhide'}
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: docker --version
      - run: docker info
      - run: docker build -t test-command -f Dockerfile_${{ matrix.distro }} --build-arg IMAGE=${{ matrix.image }} .
      # Add options not to restrict the container to avoid the following issue
      # on fedora 34, 35 (rawhide).
      # https://bugzilla.redhat.com/show_bug.cgi?id=1900021
      # - run: docker run -t --cap-add=SYS_PTRACE --security-opt seccomp=unconfined test-command
      - run: docker run -t --security-opt seccomp=unconfined test-command
